### PR TITLE
adding example extension that does not require auth

### PR DESCRIPTION
**Pull request by diogoasouza**
Creating an example extension that does not require auth for the user to see

@nwmac

### CODE REVIEW

**Review by nicholasSUSE — APPROVED** [review]

**Comment by nwmac** [comment]
@diogoasouza Can we just updated the uk locale example to be this example? Its not of any use if it can't load before login - for simplictly, I'd suggest just re-using that as the example.

**Review by nwmac — CHANGES_REQUESTED** [review]
Just replace the existing locale example

**Comment by diogoasouza** [comment]
> @diogoasouza Can we just updated the uk locale example to be this example? Its not of any use if it can't load before login - for simplictly, I'd suggest just re-using that as the example.

We can, just added a new version for it

**Review by nwmac — APPROVED** [review]
LGTM

**Pull request merged**
