### PR TITLE
publish version 0.2.0 of top-level-product extension compatible with Vue3

### PR DESCRIPTION
**Pull request by aalves08**
- bump version for top-level-product example to 0.2.0 
- publish new version of top-level-product extension

@cnotv @jordojordo I wanted to do only one extension first to make sure it works with the annotations and all before commiting to a bulk publish of the other extensions

### CODE REVIEW

**Review by jordojordo — APPROVED** [review]
Annotations look good to me.

**Review by cnotv — APPROVED** [review]
I do not see anything to be corrected. Should we maybe limit previous one to `< 2.10.0-0`?

**Comment by aalves08** [comment]
> I do not see anything to be corrected. Should we maybe limit previous one to `< 2.10.0-0`?

It will need to be deleted and re-published because the annotations aren't overwritten in `index.yaml`. I don't think it's worth it at the moment and also we have an issue to create a mechanism to allow to do just that: https://github.com/rancher/dashboard/issues/11416

**Comment by cnotv** [comment]
> > I do not see anything to be corrected. Should we maybe limit previous one to `< 2.10.0-0`?
> 
> It will need to be deleted and re-published because the annotations aren't overwritten in `index.yaml`. I don't think it's worth it at the moment and also we have an issue to create a mechanism to allow to do just that: [rancher/dashboard#11416](https://github.com/rancher/dashboard/issues/11416)

Oh ok, it would have been nice to try out if it works well or not

**Pull request merged**
